### PR TITLE
Add campaign attribution support

### LINKED ISSUE #260: Add campaign attribution to badlist updates
**Is your feature request related to a problem? Please describe.**
Currently, the badlist source update supports setting only two attribution tags: actor and malware family. They don't match my use case, where I'd like to set a campaign name.

**Describe the solution you'd like**
Adding a campaign tag to attribution tags supported by badlist source update.

**Describe alternatives you've considered**
Adding all attribution tags! :D 

**Additional context**
Would be great to add a JSON config field directly to the update source config, separating it from the service configuration ;) 

I also don't think there is any standardisation across campaign names, so I wouldn't suggest adding a list of allowed names.

### PR DESCRIPTION
**Pull request by kam193**
Fix CybercentreCanada/assemblyline#260

Note: Patch has not been tested yet

### CODE REVIEW

**Comment by cccs-rs** [comment]
If you do find that you will be able to use more the attribution tags than `actor`, `campaign`, `malware_family`, maybe I should consider re-architecting some code to allow that 🤔

**Comment by kam193** [comment]
I don't have any specific use case for more at the moment, so I've stopped on just adding this. I think it may be generally useful, but no specific need.

**Comment by cccs-rs** [comment]
The patch should be available for testing on the development channel for the service.

**Comment by kam193** [comment]
Thanks! I've just tested it - works well! Sanitization makes my names a little funny, but I don't think it's a problem. However, I've caught another issue - `if (not) source_cfg.get("...") else` does not work well when something is in the column 0 :D

**Comment by kam193** [comment]
Pushed fixes for column 0. It has already been tested by me.

**Review by cccs-rs — APPROVED** [review]

**Comment by cccs-rs** [comment]
Patch should be included in the latest stable release!

**Pull request merged**
